#!/bin/sh

set -eux

ulimit -c unlimited  # allow a core file to be written

mkdir -p build
rm -f build/core  # remove previous core file if any

cd build
# rm CMakeCache.txt  # invalidate options (sigh

cmake -D ENABLE_CLANG_TIDY:BOOL=0 ..
# CXX=clang++ cmake -D ENABLE_CLANG_TIDY:BOOL=0 ..
make VERBOSE=1

# exec ./bw wlp0s20f3
